.PHONY : all
all : config.h.in aclocal.m4 Makefile.in configure

config.h.in :
	autoheader

aclocal.m4 :
	aclocal

Makefile.in : aclocal.m4 Makefile.am
	automake --add-missing

configure : aclocal.m4 configure.ac
	autoconf